# Generated by Django 4.2.1 on 2023-05-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dateOfBirth', models.DateTimeField()),
                ('email', models.CharField(max_length=64)),
                ('GPA', models.FloatField()),
                ('level', models.IntegerField()),
                ('Status', models.BooleanField()),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
