# Generated by Django 4.2.1 on 2023-05-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Department',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
