# Generated by Django 4.2.1 on 2023-05-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Gender',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
