# Generated by Django 4.2.1 on 2023-05-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_student_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='GPA',
            new_name='gpa',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Status',
            new_name='status',
        ),
    ]
