# Generated by Django 4.2.1 on 2023-05-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_rename_department_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(max_length=1),
        ),
    ]
