# Generated by Django 4.2.1 on 2023-05-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_student_gpa_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(max_length=64),
        ),
    ]
